### PR TITLE
Wave equation DMD demonstration + miscellaneous fixes

### PR DESCRIPTION
**Pull request by dreamer2368**
### Installation using `pip`
`pylibROM` now supports installation via `pip`. At the cloned repository, we can simply run
```
pip install ./
```
or, if using a pre-installed libROM library,
```
pip install ./ --global-option="--librom_dir=/path/to/pre-installed-libROM'
```
This is also updated in `README.md`. 

The `cmake` way of installation is still available, and `pip` way is in fact based on the same `CMakeLists.txt`.

### `cmake` can take pre-installed `libROM` library
`cmake` configuration can take the pre-installed `libROM` library. If not provided, it installs its own `libROM`.
```
mkdir build && cd build
cmake .. -DLIBROM_DIR=/path/to/pre-installed-libROM
make
```

### baseline installation
If the pre-installed `libROM` is not provided, it will compile `libROM` + all the dependencies. To support LC Quartz usage, `scalapack` will be also installed if needed. This is tested on Quartz, though its ci test will be added later on a separate PR.

### `DMD` class updates
- Fix on the constructor `DMD`: the argument should take `CAROM::Vector`, not a common array of `double`.
- `DMD::takeSample` takes `numpy.array` in place of `double * u_in`.
- `mfem::Vector::GetData()` returns `SWIG Object of type 'double *'`, which has been a compatibility problem against pybind11. This is resolved by using `ctypes`:
```
# for a mfem Vector u
from ctypes import *
uData = (c_double * u.Size()).from_address(int(u.GetData())) # this does not copy the data.
# uData = list(uData) # this copies the data.
uData = np.array(uData, copy=False)
```
The numpy array `uData` shares the memory buffer with `u`, and (I believe) the ownership is on `u`.
- `mfem::Vector` can take `numpy.array` to initiate itself, so the opposite direction (`pybind11` to `SWIG`) is not a problem.

### Wave equation demonstration
[The wave equation example](https://github.com/LLNL/libROM/blob/master/examples/dmd/wave_equation.cpp) is now demonstrated using `pylibROM`. Following output is the result of `python3 wave_equation.py -o 4 -tf 5 -nwinsamp 25`:
```
Relative error of DMD solution (u) at t_final: 5.000000 is 1.591E-04
Elapsed time for solving FOM: 6.374277e+00 second
Elapsed time for training DMD: 2.605658e+00 second
Elapsed time for predicting DMD: 2.799344e-02 second
```

### Fixes on `Vector` and `Matrix`
`Vector` and `Matrix` will be the main classes for data storage. They will certainly carry a large size of data, which we should be able to provide a **view** `numpy.ndarray`. This is now supported by `pybind11::buffer_protocol`.
- `Vector.GetData()` and `Matrix.GetData()` now returns a `numpy.ndarray` as they're supposed to. The returned `numpy.ndarray` shares the memory buffer with the original `Vector`/`Matrix`, and does not claim the ownership (does not deallocate the memory buffer at its destruction).

### CODE REVIEW

**Review by mike-barrow — APPROVED** [review]

**Comment by chldkdtn** [comment]
@dreamer2368 , If I simply follow the instruction above to run wave_equation.py, then it gives me the following error:

ModuleNotFoundError: No module named 'mfem'

If you can also describe how to add pymfem when we compile pylibrom, that would be wonderful.

**Comment by dreamer2368** [comment]
> @dreamer2368 , If I simply follow the instruction above to run wave_equation.py, then it gives me the following error:
> 
> ModuleNotFoundError: No module named 'mfem'
> 
> If you can also describe how to add pymfem when we compile pylibrom, that would be wonderful.

A short instruction on how to install `PyMFEM` is added.
This is currently only the serial version of `PyMFEM`. The parallel version uses `pip`'s deprecated flag `--install-option`, which is no longer available. It requires a more in-depth installation procedure. Wave equation, though, does not use the parallel version right now, so the instruction for serial version is added.

**Comment by chldkdtn** [comment]
@dreamer2368 can you also add instruction below:

mkdir build && cd build
cmake .. -DLIBROM_DIR=/path/to/pre-installed-libROM
make

in README.md file?

**Review by michael-barrow-llnl — APPROVED** [review]
Already reviewed, thanks!

**Pull request merged**
